### ISSUE TITLE
Port to .NET Standard

### ISSUE THREAD

**Issue by dfarrNTST** [atifaziz/Escape#1]
We like the use of this package, but its doesn't support NETStandard targeting...is it possible to upgrade this to do so?

**Comment by atifaziz** [comment]
Per the [.NET Portability Analyzer](https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer), there are 0 issues to porting to .NET Core/Standard so there's a good chance this will happen when soon.
